export const data = {
    products: [
      {
        id: '1',
        name: 'Torso 1',
        image: '/shirt-1.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        id: '2',
        name: 'Torso 2',
        image: '/jacket-1.jpg',
        price: 250,
        countInStock: 2,
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '3',
        name: 'Torso 3',
        image: '/jacket-2.jpg',
        price: 25,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '4',
        name: 'Shoes 1',
        image: '/sports-1.jpg',
        price: 65,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '5',
        name: 'Skirt',
        image: '/skirt-1.jpg',
        price: 55,
        countInStock: 100,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '6',
        name: 'Sandals',
        image: '/party-wear-1.jpg',
        price: 25,
        countInStock: 100,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '7',
        name: 'Green Jacket',
        image: '/homep.jpg',
        price: 85,
        countInStock: 100,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '8',
        name: 'Digital Watch',
        image: '/watch-1.jpg',
        price: 35,
        countInStock: 100,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  }
